export const samplePrompts = [
  { id: 1, message: "Can we add a note for initiating hackathon" },
  { id: 2, message: "Can we add a note for completing implementation" },
  { id: 3, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 4, message: "Can we add a note for initiating hackathon" },
  { id: 5, message: "Can we add a note for completing implementation" },
  { id: 6, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 7, message: "Can we add a note for initiating hackathon" },
  { id: 8, message: "Can we add a note for completing implementation" },
  { id: 9, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 10, message: "Can we add a note for initiating hackathon" },
  { id: 11, message: "Can we add a note for completing implementation" },
  { id: 12, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 13, message: "Can we add a note for initiating hackathon" },
  { id: 14, message: "Can we add a note for completing implementation" },
  { id: 15, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 16, message: "Can we add a note for initiating hackathon" },
  { id: 17, message: "Can we add a note for completing implementation" },
  { id: 18, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 19, message: "Can we add a note for initiating hackathon" },
  { id: 20, message: "Can we add a note for completing implementation" },
  { id: 21, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 22, message: "Can we add a note for initiating hackathon" },
  { id: 23, message: "Can we add a note for completing implementation" },
  { id: 24, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 25, message: "Can we add a note for initiating hackathon" },
  { id: 26, message: "Can we add a note for completing implementation" },
  { id: 27, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 28, message: "Can we add a note for initiating hackathon" },
  { id: 29, message: "Can we add a note for completing implementation" },
  { id: 30, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 31, message: "Can we add a note for initiating hackathon" },
  { id: 32, message: "Can we add a note for completing implementation" },
  { id: 33, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 34, message: "Can we add a note for initiating hackathon" },
  { id: 35, message: "Can we add a note for completing implementation" },
  { id: 36, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 37, message: "Can we add a note for initiating hackathon" },
  { id: 38, message: "Can we add a note for completing implementation" },
  { id: 39, message: "Can we add a note for completing ppt for the hackathon" },
  { id: 40, message: "Can we add a note for initiating hackathon" },
  { id: 41, message: "Can we add a note for completing implementation" },
  { id: 42, message: "Can we add a note for completing ppt for the hackathon" },
];
